# Generated by Django 5.2 on 2025-07-10 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название игры')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='В наличии')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('players', models.CharField(blank=True, max_length=20, verbose_name='Количество игроков')),
                ('duration', models.CharField(blank=True, max_length=50, verbose_name='Время игры')),
                ('age', models.CharField(blank=True, max_length=20, verbose_name='Возраст')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('discount_percent', models.PositiveIntegerField(default=0, verbose_name='Скидка (%)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='main.category', verbose_name='Категория')),
            ],
        ),
    ]
