# Generated by Django 5.2 on 2025-07-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardgame',
            name='category',
        ),
        migrations.AddField(
            model_name='boardgame',
            name='categories',
            field=models.ManyToManyField(related_name='games', to='main.category', verbose_name='Категории'),
        ),
    ]
