# Generated by Django 5.2 on 2025-07-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_boardgame_category_boardgame_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='is_best',
            field=models.BooleanField(default=False, verbose_name='Хит'),
        ),
    ]
